sonar.projectKey=kcarww_simple-store-api
sonar.organization=kcarww


sonar.sources=src
sonar.exclusions=**/test_*.py, **/tests/**

sonar.tests=src
sonar.test.inclusions=**/tests/**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.branch.name=develop
