sonar.projectKey=kcarww_simple-store-api
sonar.organization=kcarww


sonar.sources=src
sonar.exclusions=**/test_*.py, **/tests/**/__init__.py


sonar.tests=src
sonar.tests.inclusions=**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml
