sonar.projectKey=simple-store-api

sonar.sources=src
sonar.exclusions=**/test_*.py


sonar.tests=src
sonar.tests.inclusions=**/test_*.py
sonar.host.url=http://localhost:9000
sonar.login=sqp_304107fb7e230b284c88d4a261de0c49f63daccd
sonar.python.coverage.reportPaths=coverage.xml
